
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopping-cart-ui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: npm install --save @testing-library/react @testing-library/jest-dom
    spec:
      containers:
        - name: shopping-cart-ui
          image: registry.gitlab.com/abhijeetkesarkar/devbootcamp/shopping-cart/shopping-cart-ui
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_SERVER
              valueFrom:
                configMapKeyRef:
                  name: url-config
                  key: api.url
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: shopping-cart-ui-registry
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-app
  labels:
    app: shopping-cart-ui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: shopping-cart-ui
  type: LoadBalancer
