version: "2"
services:
  adminer:
    image: 'adminer'
    restart: always
    depends_on:
      - "db"
    ports:
      - 9091:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: shopping-cart
    ports:
      - 5433:5432
  app:
    build: .
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopping-cart?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    - SPRING.DATASOURCE_USERNAME=postgres
    - SPRING.DATASOURCE_PASSWORD=postgres@123
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8082:8080
    depends_on:
        - db

  frontend:
    image: shopping-cart-ui:latest
    restart: always
    ports:
      - 3002:3000